# Generated by Django 5.2 on 2025-04-28 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0002_userbrandedimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbrandedimage',
            name='branded_image',
        ),
        migrations.AddField(
            model_name='userbrandedimage',
            name='branded_image_url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
