# Generated by Django 5.2 on 2025-04-28 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0003_remove_userbrandedimage_branded_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='lyrics',
            field=models.TextField(blank=True),
        ),
    ]
